"""
Django settings for sifex project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
import os
import environ
import dj_database_url
from urllib.parse import urlparse

# Initialize environment variables
env = environ.Env()
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, '.env'))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[])

CSRF_TRUSTED_ORIGINS = ["https://sifex.up.railway.app", "https://sifex.co.tz", "https://www.sifex.co.tz", "http://127.0.0.1"]
# CSRF_TRUSTED_ORIGINS = env.list('TRUSTED_ORIGINS', default=[])

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'core',
    'sifex_system',
    'tcra_integration',
    'widget_tweaks',
    'bulma',
    'wkhtmltopdf',
    'storages',  # Add this line
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "sifex.redirect_to_www.RedirectToWWWMiddleware",
]


ROOT_URLCONF = 'sifex.urls'
CORS_ALLOW_ALL_ORIGINS = True

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sifex.wsgi.application'

# Database

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Use PostgreSQL database
#DATABASE_URL = "postgresql://postgres:anWTLHLryNYAsoexOMsVeOznaBftiYIB@junction.proxy.rlwy.net:32934/railway"

# # Parse the database URL and configure DATABASES setting
#url = urlparse(DATABASE_URL)


DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError("DATABASE_URL is not set in environment variables")

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=False  # set True only if using external managed DB with SSL
    )
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': env('DB_NAME'),
#         'USER': env('DB_USER'),
#         'PASSWORD': env('DB_PASSWORD'),
#         'HOST': env('DB_HOST'),
#         'PORT': env('DB_PORT'),
#     }
# }




# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Africa/Nairobi'
USE_I18N = False
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Extra places for collectstatic to find static files.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"



# Media files (Uploaded by users)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/{AWS_LOCATION}/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

# TCRA integration settings
TCRA_API_KEY_HEADER = env('TCRA_API_KEY_HEADER', default='X-API-Key')
TCRA_SIGNATURE_HEADER = env('TCRA_SIGNATURE_HEADER', default='')
# Backward compatibility with previous setting name.
TCRA_WEBHOOK_SIGNATURE_HEADER = env('TCRA_WEBHOOK_SIGNATURE_HEADER', default=TCRA_SIGNATURE_HEADER)
TCRA_WEBHOOK_SECRET = env('TCRA_WEBHOOK_SECRET', default='')
TCRA_MAX_ATTEMPTS = env.int('TCRA_MAX_ATTEMPTS', default=4)
TCRA_RETRY_BACKOFFS = [60, 300, 900, 3600]
TCRA_BASE_URL = env('TCRA_BASE_URL', default='')
# Legacy symmetric key setting (deprecated by PKCS#12 signing).
TCRA_PRIVATE_KEY = env('TCRA_PRIVATE_KEY', default='')
TCRA_PFX_PASSWORD = env('TCRA_PFX_PASSWORD', default='')
TCRA_PFX_PATH = env('TCRA_PFX_PATH', default='')
TCRA_WEBHOOK_PUBLIC_CERT_B64 = env('TCRA_WEBHOOK_PUBLIC_CERT_B64', default='')
TCRA_WEBHOOK_PUBLIC_CERT_PEM = env('TCRA_WEBHOOK_PUBLIC_CERT_PEM', default='')
TCRA_WEBHOOK_PUBLIC_CERT_PATH = env('TCRA_WEBHOOK_PUBLIC_CERT_PATH', default='')
TCRA_WEBHOOK_PUBLIC_KEY_B64 = env('TCRA_WEBHOOK_PUBLIC_KEY_B64', default='')
TCRA_WEBHOOK_PUBLIC_KEY_PEM = env('TCRA_WEBHOOK_PUBLIC_KEY_PEM', default='')
TCRA_WEBHOOK_PUBLIC_KEY_PATH = env('TCRA_WEBHOOK_PUBLIC_KEY_PATH', default='')
TCRA_OPERATOR_CODE = env.int('TCRA_OPERATOR_CODE', default=1004)
TCRA_PATHS = {
    # All existing submission types are routed to the events endpoint by default.
    'SHIPMENT_CREATED': '/v1/api/events',
    'SHIPMENT_UPDATED': '/v1/api/events',
    'DELIVERY_CONFIRMED': '/v1/api/events',
    'MANIFEST': '/v1/api/events',
    'BILLING': '/v1/api/events',
    'OTHER': '/v1/api/events',
    # Explicit new endpoints from the TCRA spec.
    'EVENTS': '/v1/api/events',
    'SNAPSHOT': '/v1/api/snapshot',
    'CALLBACK': '/v1/api/callback',
    'DEFAULT': '/v1/api/events',
}

# Celery settings
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TASK_ALWAYS_EAGER = env.bool('CELERY_TASK_ALWAYS_EAGER', default=False)
CELERY_TASK_EAGER_PROPAGATES = True

# Logging configuration
# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'console':{
#             'class':'logging.StreamHandler',
#         },
#     },
#     'root': {
#         'handlers': ['console'],
#         'level': 'INFO',
#     },
# }

# Message storage configuration
MESSAGE_STORAGE = 'django.contrib.messages.storage.fallback.FallbackStorage'



SECURE_SSL_REDIRECT = False
LOGIN_URL = '/accounts/login/'
