# Generated by Codex on 2025-02-14
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TcraEndpointConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("base_url", models.URLField()),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("API_KEY", "API Key"), ("BASIC", "Basic"), ("OAUTH2", "OAuth2")],
                        default="API_KEY",
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=255, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                ("client_id", models.CharField(blank=True, max_length=255, null=True)),
                ("client_secret", models.CharField(blank=True, max_length=255, null=True)),
                ("token_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("timeout_seconds", models.PositiveIntegerField(default=30)),
                ("verify_ssl", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TcraSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("SHIPMENT_CREATED", "Shipment Created"),
                            ("SHIPMENT_UPDATED", "Shipment Updated"),
                            ("DELIVERY_CONFIRMED", "Delivery Confirmed"),
                            ("MANIFEST", "Manifest"),
                            ("BILLING", "Billing"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("provider_reference", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("SENT", "Sent"), ("FAILED", "Failed")],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, null=True)),
                ("tcra_response_code", models.PositiveIntegerField(blank=True, null=True)),
                ("tcra_response_body", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TcraWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("headers", models.JSONField()),
                ("body", models.JSONField(blank=True, null=True)),
                ("signature_valid", models.BooleanField(default=False)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("processing_error", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(max_length=255)),
                ("object_type", models.CharField(max_length=255)),
                ("object_id", models.CharField(max_length=255)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tcra_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
