# Generated by Django 4.2.4 on 2025-06-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_man',
            field=models.BooleanField(default=False, verbose_name='delivery man'),
        ),
    ]
