# Generated by Django 4.2.4 on 2025-06-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0002_alter_invoice_total_amount_tzs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_of_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount_tz',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
