# Generated by Django 4.2.4 on 2026-01-05 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sifex_system', '0003_invoice_date_of_payment_alter_lineitem_amount_tz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date']},
        ),
    ]
